---
- hosts: all
  become: true
  pre_tasks:

    - name: Update repository index (CentOS)
      tags: always
      yum: 
        update_cache: yes
        use_backend: dnf4
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: Update (Ubuntu)
      tags: always
      apt: 
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:  
    - workstation


